# Generated by Django 4.2.1 on 2023-06-05 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='message',
        ),
    ]
