# Generated by Django 4.2.1 on 2023-06-06 14:35

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_searchhistory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='blog-uploads/%Y/', verbose_name='Picture as thumbnail'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='profile_images'),
        ),
    ]
